manager: scripts: fixed after changes in repository structure, added missing dependencies

diff --git a/manager/scripts/codecheck b/manager/scripts/codecheck
--- a/manager/scripts/codecheck
+++ b/manager/scripts/codecheck
@@ -36,9 +36,14 @@ echo
 
 # check types with pyright
 echo -e "${yellow}Type checking using pyright...${reset}"
-pyright knot_resolver_manager
-check_rv $?
-echo
+if command -v pyright > /dev/null; then
+	pyright knot_resolver_manager
+	check_rv $?
+	echo
+else
+	echo -e "${blue}  ...skipped - pyright binary was not found${reset}"
+	echo
+fi
 
 # check types with mypy
 echo -e "${yellow}Type checking using mypy...${reset}"
